TABLE_WIDTH = 900
TABLE_HEIGHT = 500

TABLE_MARGIN = 30           # 화면 가장자리부터 쿠션 중심까지
CUSHION_THICKNESS = 20      # pygame rect 그릴 때 width 값

# pygame.draw.rect 에 쓸 전체 쿠션 영역
TABLE_RECT = (
    TABLE_MARGIN,
    TABLE_MARGIN,
    TABLE_WIDTH - TABLE_MARGIN * 2,
    TABLE_HEIGHT - TABLE_MARGIN * 2,
)

# 실제 공이 굴러다닐 수 있는 안쪽 경계 (쿠션 안쪽 라인)
PLAY_LEFT   = TABLE_MARGIN + CUSHION_THICKNESS // 2
PLAY_RIGHT  = TABLE_WIDTH  - TABLE_MARGIN - CUSHION_THICKNESS // 2
PLAY_TOP    = TABLE_MARGIN + CUSHION_THICKNESS // 2
PLAY_BOTTOM = TABLE_HEIGHT - TABLE_MARGIN - CUSHION_THICKNESS // 2
